create extension if not exists pgcrypto;

create table if not exists public.devices (
  id uuid primary key default gen_random_uuid(),
  device_uuid text not null unique,
  owner_id uuid not null references auth.users(id) on delete cascade,
  device_name text not null,
  model text,
  android_version text,
  battery integer not null default 0 check (battery >= 0 and battery <= 100),
  is_charging boolean not null default false,
  last_seen timestamptz not null default now(),
  device_token text not null unique,
  created_at timestamptz not null default now()
);

create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  device_id uuid not null references public.devices(id) on delete cascade,
  package_name text,
  app_name text,
  title text,
  content text,
  posted_at timestamptz not null default now()
);

create table if not exists public.commands (
  id bigint generated by default as identity primary key,
  device_id uuid not null references public.devices(id) on delete cascade,
  action text not null check (action in ('HOME','BACK','RECENTS')),
  status text not null default 'pending' check (status in ('pending','delivered','done','failed')),
  created_at timestamptz not null default now(),
  delivered_at timestamptz,
  completed_at timestamptz
);

alter table public.devices enable row level security;
alter table public.notifications enable row level security;
alter table public.commands enable row level security;

-- Private single-owner dashboard: any authenticated admin account can see these tables.
-- Keep only your own Supabase auth account in the project.
create policy "owner can read devices"
on public.devices for select to authenticated using (auth.uid() = owner_id);

create policy "owner can read notifications"
on public.notifications for select to authenticated using (exists (select 1 from public.devices d where d.id = notifications.device_id and d.owner_id = auth.uid()));

create policy "owner can read commands"
on public.commands for select to authenticated using (exists (select 1 from public.devices d where d.id = commands.device_id and d.owner_id = auth.uid()));

create policy "owner can create commands"
on public.commands for insert to authenticated with check (exists (select 1 from public.devices d where d.id = commands.device_id and d.owner_id = auth.uid()));

-- Realtime publication for live dashboard refresh.
alter publication supabase_realtime add table public.devices;
alter publication supabase_realtime add table public.notifications;
